# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAITranslation', '0004_translation_suggestedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='algorithmAlias',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='algorithmPath',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
